repos:
-   repo: local
    hooks:
    -   id: requirements
        name: Create new requirements
        entry: bash -c "uv export --no-hashes --no-header --no-annotate --format requirements.txt > requirements.txt; git add requirements.txt"
        language: system
        files: "uv.lock"
        stages: [manual, pre-commit]
    -   id: format
        name: format with ruff
        entry: bash -c "uv run ruff format ."
        language: system
        files: "\.py$"
        stages: [pre-commit]
    -   id: lint with ruff
        name: linter with ruff
        entry: bash -c "uv run ruff check ."
        language: system
        files: "\.py$"
        stages: [pre-commit]